// 样式属性映射
export const baseAttrsMap = {
  ac: "accent-color",
  as: "additive-symbols",
  ali_c: "align-content",
  ali_i: "align-items",
  ali_st: "aling-start",
  ali_s: "align-self",
  ab: "alignment-baseline",
  all: "all",
  ani: "animation",
  ani_c: "animation-composition",
  ani_d: "animation-delay",
  ani_dir: "animation-direction",
  ani_dur: "animation-duration",
  ani_fm: "animation-fill-mode",
  ani_ic: "animation-iteration-count",
  ani_n: "animation-name",
  ani_ps: "animation-play-state",
  ani_r: "animation-range",
  ani_re: "animation-range-end",
  ani_rs: "animation-range-start",
  ani_t: "animation-timeline",
  ani_tf: "animation-timing-function",
  app_r: "app-region",
  ar: "aspect-ratio",
  a: "appearance",
  ao: "ascent-override",
  bf: "backdrop-filter",
  bv: "backface-visibility",
  bg: "background",
  bg_a: "background-attachment",
  bg_bm: "background-blend-mode",
  bg_c: "background-clip",
  bgc: "background-color",
  bg_i: "background-image",
  bg_o: "background-origin",
  bg_p: "background-position",
  bg_px: "background-position-x",
  bg_py: "background-position-y",
  bg_r: "background-repeat",
  bg_s: "background-size",
  bp: "base-palette",
  b_sf: "baseline-shift",
  bs: "box-sizing",
  bd: "border",
  bd_b: "border-block",
  bd_bc: "border-block-color",
  bd_be: "border-block-end",
  bd_bec: "border-block-end-color",
  bd_bes: "border-block-end-style",
  bd_bew: "border-block-end-width",
  bd_b_sr: "border-block-start",
  bd_b_sl: "border-block-style",
  bd_bsc: "border-block-start-color",
  bd_bss: "border-block-start-style",
  bd_bsw: "border-block-start-width",
  bd_bw: "border-block-width",
  bd_bt: "border-bottom",
  bd_bt_c: "border-bottom-color",
  bd_bt_lr: "border-bottom-left-radius",
  bd_bt_rr: "border-bottom-right-radius",
  bd_bt_s: "border-bottom-style",
  bd_bt_w: "border-bottom-width",
  bd_clp: "border-collapse",
  bd_c: "border-color",
  bd_eer: "border-end-end-radius",
  bd_esr: "border-end-start-radius",
  bd_i: "border-image",
  bd_io: "border-image-outset",
  bd_ir: "border-image-repeat",
  bd_i_sl: "border-image-slice",
  bd_i_sc: "border-image-source",
  bd_iw: "border-image-width",
  bd_il: "border-inline",
  bd_il_c: "border-inline-color",
  bd_il_e: "border-inline-end",
  bd_il_ec: "border-inline-end-color",
  bd_il_es: "border-inline-end-style",
  bd_il_ew: "border-inline-end-width",
  bd_il_sr: "border-inline-start",
  bd_il_sl: "border-inline-style",
  bd_il_sc: "border-inline-start-color",
  bd_il_ss: "border-inline-start-style",
  bd_il_sw: "border-inline-start-width",
  bd_il_w: "border-inline-width",
  bd_l: "border-left",
  bd_lc: "border-left-color",
  bd_ls: "border-left-style",
  bd_lw: "border-left-width",
  bd_rd: "border-radius",
  bd_rg: "border-right",
  bd_rc: "border-right-color",
  bd_rs: "border-right-style",
  bd_rw: "border-right-width",
  bd_s: "border-spacing",
  bd_sl: "border-style",
  bd_ser: "border-start-end-radius",
  bd_ssr: "border-start-start-radius",
  bd_t: "border-top",
  bd_tc: "border-top-color",
  bd_tlr: "border-top-left-radius",
  bd_trr: "border-top-right-radius",
  bd_ts: "border-top-style",
  bd_tw: "border-top-width",
  bd_w: "border-width",
  b_sd: "box-shadow",
  b_d_b: "box-decoration-break",
  bt: "bottom",
  ba: "break-after",
  bb: "break-before",
  bi: "break-inside",
  br: "buffered-rendering",
  cs: "caption-side",
  ct_s: "counter-set",
  cc: "caret-color",
  clear: "clear",
  clip: "clip",
  cp: "clip-path",
  cr: "clip-rule",
  ct_r: "counter-reset",
  color: "color",
  ci: "color-interpolation",
  ct: "content",
  ct_i: "counter-increment",
  cif: "color-interpolation-filters",
  col_c: "column-count",
  col_f: "column-fill",
  col_g: "column-gap",
  col_r: "column-rule",
  col_rc: "column-rule-color",
  col_rs: "column-rule-style",
  col_rw: "column-rule-width",
  col_s: "column-span",
  col_w: "column-width",
  col: "columns",
  c: "cursor",
  cibs: "contain-intrinsic-block-size",
  cih: "contain-intrinsic-height",
  ci_il_s: "contain-intrinsic-inline-size",
  cis: "contain-intrinsic-size",
  ciw: "contain-intrinsic-width",
  cn: "container-name",
  ct_t: "container-type",
  cv: "content-visibility",
  cx: "cx",
  cy: "cy",
  d: "d",
  dis: "display",
  do: "descent-override",
  dir: "direction",
  db: "dominant-baseline",
  ec: "empty-cells",
  f: "fallback",
  ft: "filter",
  fill: "fill",
  fi_o: "fill-opacity",
  fo: "flood-opacity",
  fr: "fill-rule",
  flex: "flex",
  fb: "flex-basis",
  f_dir: "flex-direction",
  ff: "flex-flow",
  fg: "flex-grow",
  fs: "flex-shrink",
  fw: "flex-wrap",
  float: "float",
  fc: "flood-color",
  font: "font",
  ft_d: "font-display",
  ft_f: "font-family",
  ft_fs: "font-feature-settings",
  ft_k: "font-kerning",
  ft_os: "font-optical-sizing",
  ft_p: "font-palette",
  ft_s: "font-size",
  ft_sh: "font-synthesis",
  ft_ssc: "font-synthesis-small-caps",
  ft_ss: "font-synthesis-style",
  ft_sw: "font-synthesis-weight",
  ft_v: "font-variant",
  ft_va: "font-variant-alternates",
  ft_vc: "font-variant-caps",
  ft_vea: "font-variant-east-asian",
  ft_vl: "font-variant-ligatures",
  ft_vn: "font-variant-numeric",
  ft_vp: "font-variant-position",
  ft_vs: "font-variation-settings",
  ft_w: "font-weight",
  fca: "forced-color-adjust",
  gap: "gap",
  grid: "grid",
  ga: "grid-area",
  gac: "grid-auto-columns",
  gaf: "grid-auto-flow",
  gar: "grid-auto-rows",
  gcol: "grid-column",
  gcol_e: "grid-column-end",
  gcol_g: "grid-column-gap",
  gcol_s: "grid-column-start",
  gg: "grid-gap",
  gr: "grid-row",
  gre: "grid-row-end",
  grg: "grid-row-gap",
  grs: "grid-row-start",
  gt: "grid-template",
  gta: "grid-template-areas",
  gtc: "grid-template-columns",
  gtr: "grid-template-rows",
  h: "height",
  hh: "hyphens",
  hc: "hyphenate-character",
  hlc: "hyphenate-limit-chars",
  io: "image-orientation",
  ir: "image-rendering",
  i: "inherits",
  ilt: "isolation",
  il: "initial-letter",
  iv: "initial-value",
  il_s: "inline-size",
  inset: "inset",
  ib: "inset-block",
  ibe: "inset-block-end",
  ibs: "inset-block-start",
  i_il: "inset-inline",
  i_il_e: "inset-inline-end",
  i_il_s: "inset-inline-start",
  jc: "justify-content",
  ji: "justify-items",
  js: "justify-self",
  left: "left",
  ls: "letter-spacing",
  l_sl: "list-style",
  lc: "lighting-color",
  lb: "line-break",
  lgo: "line-gap-override",
  lh: "line-height",
  lsi: "list-style-image",
  lsp: "list-style-position",
  lst: "list-style-type",
  mg: "margin",
  mg_b: "margin-block",
  mg_be: "margin-block-end",
  mg_bs: "margin-block-start",
  mg_bt: "margin-bottom",
  mg_il: "margin-inline",
  mg_il_e: "margin-inline-end",
  mg_il_s: "margin-inline-start",
  mg_l: "margin-left",
  mg_r: "margin-right",
  mg_t: "margin-top",
  m: "marker",
  me: "marker-end",
  mm: "marker-mid",
  ms: "marker-start",
  mask: "mask",
  mc: "mask-clip",
  mk_c: "mask-composite",
  mk_i: "mask-image",
  mk_o: "mask-origin",
  mk_p: "mask-position",
  mk_r: "mask-repeat",
  mk_t: "mask-type",
  mk_d: "math-depth",
  mk_m: "mask-mode",
  mk_s: "math-style",
  max_bs: "max-block-size",
  max_h: "max-height",
  max_il_s: "max-inline-size",
  max_w: "max-width",
  min_bs: "min-block-size",
  min_h: "min-height",
  min_il_s: "min-inline-size",
  min_w: "min-width",
  mbm: "mix-blend-mode",
  n: "negative",
  ob_f: "object-fit",
  ob_p: "object-position",
  os_p: "offset-position",
  ovb: "object-view-box",
  os: "offset",
  o: "overlay",
  opt: "opacity",
  orp: "orphans",
  oa: "offset-anchor",
  od: "offset-distance",
  or: "offset-rotate",
  order: "order",
  ol_c: "outline-color",
  or_c: "override-colors",
  oo: "outline-offset",
  o_sl: "outline-style",
  ow: "outline-width",
  of: "overflow",
  of_a: "overflow-anchor",
  of_cmg: "overflow-clip-margin",
  of_w: "overflow-wrap",
  of_x: "overflow-x",
  of_y: "overflow-y",
  ob: "overscroll-behavior",
  obb: "overscroll-behavior-block",
  ob_il: "overscroll-behavior-inline",
  obx: "overscroll-behavior-x",
  oby: "overscroll-behavior-y",
  pad: "pad",
  pd: "padding",
  pd_b: "padding-block",
  pd_be: "padding-block-end",
  pd_bs: "padding-block-start",
  pd_bt: "padding-bottom",
  pd_il: "padding-inline",
  pd_il_e: "padding-inline-end",
  pd_il_s: "padding-inline-start",
  pd_l: "padding-left",
  pd_r: "padding-right",
  pd_t: "padding-top",
  page: "page",
  pba: "page-break-after",
  pbb: "page-break-before",
  pbi: "page-break-inside",
  po: "page-orientation",
  pp_o: "perspective-origin",
  pp: "perspective",
  pf: "prefix",
  pc: "place-content",
  pi: "place-items",
  ps: "place-self",
  pst: "position",
  pe: "pointer-events",
  q: "quotes",
  r: "r",
  rz: "resize",
  rt: "rotate",
  range: "range",
  right: "right",
  rg: "row-gap",
  rp: "ruby-position",
  rx: "rx",
  ry: "ry",
  ra: "ruby-align",
  ro: "ruby-overhang",
  rs: "ruby-span",
  scale: "scale",
  scr_b: "scroll-behavior",
  scr_mg: "scroll-margin",
  scr_mg_b: "scroll-margin-block",
  scr_mg_be: "scroll-margin-block-end",
  scr_mg_bs: "scroll-margin-block-start",
  scr_mg_bt: "scroll-margin-bottom",
  scr_mg_il: "scroll-margin-inline",
  scr_mg_il_e: "scroll-margin-inline-end",
  scr_mg_il_s: "scroll-margin-inline-start",
  scr_mg_l: "scroll-margin-left",
  scr_mg_r: "scroll-margin-right",
  scr_mg_t: "scroll-margin-top",
  scr_pd: "scroll-padding",
  scr_pd_b: "scroll-padding-block",
  scr_pd_be: "scroll-padding-block-end",
  scr_pd_bs: "scroll-padding-block-start",
  scr_pd_bt: "scroll-padding-bottom",
  scr_pd_il: "scroll-padding-inline",
  scr_pd_il_e: "scroll-padding-inline-end",
  scr_pd_il_s: "scroll-padding-inline-start",
  scr_pd_l: "scroll-padding-left",
  scr_pd_r: "scroll-padding-right",
  scr_pd_t: "scroll-padding-top",
  scr_sali: "scroll-snap-align",
  scr_ss: "scroll-snap-stop",
  scr_st: "scroll-snap-type",
  scr_t: "scroll-timeline",
  scr_ta: "scroll-timeline-axis",
  scr_tn: "scroll-timeline-name",
  scr_g: "scrollbar-gutter",
  scr_w: "scrollbar-width",
  scr_c: "scrollbar-color",
  sit: "shape-image-threshold",
  smg: "shape-margin",
  so: "shape-outside",
  s_opt: "stop-opacity",
  sr: "shape-rendering",
  size: "size",
  sa: "size-adjust",
  s_as: "speak-as",
  speak: "speak",
  src: "src",
  sc: "stop-color",
  sk: "stroke",
  sk_dr: "stroke-dasharray",
  sk_lc: "stroke-linecap",
  sk_df: "stroke-dashoffset",
  sk_lj: "stroke-linejoin",
  sk_m: "stroke-miterlimit",
  sk_o: "stroke-opacity",
  sk_w: "stroke-width",
  s: "suffix",
  sys: "system",
  ts: "tab-size",
  tl_s: "timeline-scope",
  tl: "table-layout",
  tali: "text-align",
  tali_l: "text-align-last",
  ta: "text-anchor",
  t_at: "touch-action",
  tcu: "text-combine-upright",
  td: "text-decoration",
  tdc: "text-decoration-color",
  tdl: "text-decoration-line",
  tdsi: "text-decoration-skip-ink",
  tds: "text-decoration-style",
  tdt: "text-decoration-thickness",
  te: "text-emphasis",
  tec: "text-emphasis-color",
  tep: "text-emphasis-position",
  tes: "text-emphasis-style",
  ti: "text-indent",
  to: "text-orientation",
  tof: "text-overflow",
  t_jtf: "text-justify",
  tr: "text-rendering",
  tsa: "text-size-adjust",
  t_tf: "text-transform",
  tuo: "text-underline-offset",
  tup: "text-underline-position",
  tw: "text-wrap",
  top: "top",
  tf: "transform",
  tf_b: "transform-box",
  tf_o: "transform-origin",
  tf_s: "transform-style",
  t_sd: "text-shadow",
  trs: "transition",
  trs_b: "transition-behavior",
  trs_d: "transition-delay",
  trs_dur: "transition-duration",
  trs_p: "transition-property",
  trs_tf: "transition-timing-function",
  t: "translate",
  ub: "unicode-bidi",
  ur: "unicode-range",
  us: "user-select",
  ve: "vector-effect",
  vali: "vertical-align",
  vt: "view-timeline",
  vta: "view-timeline-axis",
  vti: "view-timeline-inset",
  vtn: "view-timeline-name",
  v_trs_n: "view-transition-name",
  v: "visibility",
  wk_ali_c: "webkit-align-content",
  wk_ali_i: "webkit-align-items",
  wk_ali_s: "webkit-align-self",
  wk_ani: "webkit-animation",
  wk_ani_d: "webkit-animation-delay",
  wk_ani_dir: "webkit-animation-direction",
  wk_ani_dur: "webkit-animation-duration",
  wk_ani_fm: "webkit-animation-fill-mode",
  wk_ani_ic: "webkit-animation-iteration-count",
  wk_ani_n: "webkit-animation-name",
  wk_ani_ps: "webkit-animation-play-state",
  wk_ani_tf: "webkit-animation-timing-function",
  wk_ar: "webkit-app-region",
  wk_a: "webkit-appearance",
  wk_bv: "webkit-backface-visibility",
  wk_bg_c: "webkit-background-clip",
  wk_bg_o: "webkit-background-origin",
  wk_bg_s: "webkit-background-size",
  wk_bd_a: "webkit-border-after",
  wk_bd_ac: "webkit-border-after-color",
  wk_bd_as: "webkit-border-after-style",
  wk_bd_aw: "webkit-border-after-width",
  wk_bd_b: "webkit-border-before",
  wk_bd_bc: "webkit-border-before-color",
  wk_bd_bs: "webkit-border-before-style",
  wk_bd_bw: "webkit-border-before-width",
  wk_bd_bt_lr: "webkit-border-bottom-left-radius",
  wk_bd_bt_rr: "webkit-border-bottom-right-radius",
  wk_bd_e: "webkit-border-end",
  wk_bd_ec: "webkit-border-end-color",
  wk_bd_es: "webkit-border-end-style",
  wk_bd_ew: "webkit-border-end-width",
  wk_bd_hs: "webkit-border-horizontal-spacing",
  wk_bd_i: "webkit-border-image",
  wk_bd_r: "webkit-border-radius",
  wk_bd_s: "webkit-border-start",
  wk_bd_sc: "webkit-border-start-color",
  wk_bd_ss: "webkit-border-start-style",
  wk_bd_sw: "webkit-border-start-width",
  wk_bd_tlr: "webkit-border-top-left-radius",
  wk_bd_trr: "webkit-border-top-right-radius",
  wk_bd_vs: "webkit-border-vertical-spacing",
  wk_bali: "webkit-box-align",
  wk_bdb: "webkit-box-decoration-break",
  wk_b_dir: "webkit-box-direction",
  wk_bf: "webkit-box-flex",
  wk_bog: "webkit-box-ordinal-group",
  wk_bo: "webkit-box-orient",
  wk_bp: "webkit-box-pack",
  wk_br: "webkit-box-reflect",
  wk_b_sd: "webkit-box-shadow",
  wk_b_sz: "webkit-box-sizing",
  wk_cp: "webkit-clip-path",
  wk_col_ba: "webkit-column-break-after",
  wk_col_bb: "webkit-column-break-before",
  wk_col_bi: "webkit-column-break-inside",
  wk_col_c: "webkit-column-count",
  wk_col_g: "webkit-column-gap",
  wk_col_r: "webkit-column-rule",
  wk_col_rc: "webkit-column-rule-color",
  wk_col_rs: "webkit-column-rule-style",
  wk_col_rw: "webkit-column-rule-width",
  wk_col_s: "webkit-column-span",
  wk_col_w: "webkit-column-width",
  wk_c: "webkit-columns",
  wk_fit: "webkit-filter",
  wk_f: "webkit-flex",
  wk_fb: "webkit-flex-basis",
  wk_f_dir: "webkit-flex-direction",
  wk_ff: "webkit-flex-flow",
  wk_fg: "webkit-flex-grow",
  wk_fs: "webkit-flex-shrink",
  wk_fw: "webkit-flex-wrap",
  wk_ft_fs: "webkit-font-feature-settings",
  wk_ft_s: "webkit-font-smoothing",
  wk_hc: "webkit-hyphenate-character",
  wk_jc: "webkit-justify-content",
  wk_lb: "webkit-line-break",
  wk_lc: "webkit-line-clamp",
  wk_l: "webkit-locale",
  wk_lh: "webkit-logical-height",
  wk_lw: "webkit-logical-width",
  wk_mg_a: "webkit-margin-after",
  wk_mg_b: "webkit-margin-before",
  wk_mg_e: "webkit-margin-end",
  wk_mg_s: "webkit-margin-start",
  wk_m: "webkit-mask",
  wk_mbi: "webkit-mask-box-image",
  wk_mbio: "webkit-mask-box-image-outset",
  wk_mbir: "webkit-mask-box-image-repeat",
  wk_mbi_sl: "webkit-mask-box-image-slice",
  wk_mbiw: "webkit-mask-box-image-width",
  wk_mbi_sc: "webkit-mask-box-image-source",
  wk_mc: "webkit-mask-clip",
  wk_m_com: "webkit-mask-composite",
  wk_mi: "webkit-mask-image",
  wk_mo: "webkit-mask-origin",
  wk_mp: "webkit-mask-position",
  wk_mpx: "webkit-mask-position-x",
  wk_mpy: "webkit-mask-position-y",
  wk_mr: "webkit-mask-repeat",
  wk_ms: "webkit-mask-size",
  wk_max_lh: "webkit-max-logical-height",
  wk_max_lw: "webkit-max-logical-width",
  wk_min_lh: "webkit-min-logical-height",
  wk_min_lw: "webkit-min-logical-width",
  wk_opt: "webkit-opacity",
  wk_o: "webkit-order",
  wk_pd_a: "webkit-padding-after",
  wk_pd_b: "webkit-padding-before",
  wk_pd_e: "webkit-padding-end",
  wk_pd_s: "webkit-padding-start",
  wk_p: "webkit-perspective",
  wk_po: "webkit-perspective-origin",
  wk_pox: "webkit-perspective-origin-x",
  wk_poy: "webkit-perspective-origin-y",
  wk_pca: "webkit-print-color-adjust",
  wk_ro: "webkit-rtl-ordering",
  wk_rp: "webkit-ruby-position",
  wk_sit: "webkit-shape-image-threshold",
  wk_smg: "webkit-shape-margin",
  wk_so: "webkit-shape-outside",
  wk_thc: "webkit-tap-highlight-color",
  wk_tc: "webkit-text-combine",
  wk_tdie: "webkit-text-decorations-in-effect",
  wk_te: "webkit-text-emphasis",
  wk_tec: "webkit-text-emphasis-color",
  wk_tep: "webkit-text-emphasis-position",
  wk_tes: "webkit-text-emphasis-style",
  wk_tfc: "webkit-text-fill-color",
  wk_to: "webkit-text-orientation",
  wk_ts: "webkit-text-security",
  wk_tsa: "webkit-text-size-adjust",
  wk_t_sk: "webkit-text-stroke",
  wk_t_sk_c: "webkit-text-stroke-color",
  wk_t_sk_w: "webkit-text-stroke-width",
  wk_tf: "webkit-transform",
  wk_tf_o: "webkit-transform-origin",
  wk_tf_ox: "webkit-transform-origin-x",
  wk_tf_oy: "webkit-transform-origin-y",
  wk_tf_oz: "webkit-transform-origin-z",
  wk_tf_s: "webkit-transform-style",
  wk_trs: "webkit-transition",
  wk_trs_d: "webkit-transition-delay",
  wk_trs_dur: "webkit-transition-duration",
  wk_trs_p: "webkit-transition-property",
  wk_trs_tf: "webkit-transition-timing-function",
  wk_ud: "webkit-user-drag",
  wk_um: "webkit-user-modify",
  wk_us: "webkit-user-select",
  wk_wm: "webkit-writing-mode",
  ws: "white-space",
  wd_s: "word-spacing",
  wsc: "white-space-collapse",
  widows: "widows",
  w: "width",
  wc: "will-change",
  wb: "word-break",
  ww: "word-wrap",
  wm: "writing-mode",
  x: "x",
  y: "y",
  zi: "z-index",
  zoom: "zoom",
};
// 内置属性值
export const builtInValue = {
  display: ["block", "inline", "inline-block", "flex", "grid", "none"],
  position: ["static", "relative", "absolute", "fixed", "sticky"],
  float: ["left", "right", "none"],
  clear: ["left", "right", "both", "none"],
  visibility: ["visible", "hidden", "collapse"],
  overflow: ["visible", "hidden", "scroll", "auto"],
  "text-align": ["left", "right", "center", "justify"],
  "vertical-align": ["baseline", "top", "middle", "bottom"],
  "white-space": ["normal", "nowrap", "pre", "pre-wrap", "pre-line"],
  "list-style-type": [
    "disc",
    "circle",
    "square",
    "decimal",
    "upper-alpha",
    "lower-alpha",
    "upper-roman",
    "lower-roman",
    "none",
  ],
  "list-style-position": ["inside", "outside"],
  "list-style-image": ["none"],
  "pointer-events": ["auto", "none"],
  cursor: [
    "auto",
    "default",
    "pointer",
    "text",
    "move",
    "wait",
    "help",
    "progress",
    "not-allowed",
  ],
  "background-repeat": ["repeat", "repeat-x", "repeat-y", "no-repeat"],
  "background-position": [
    "left top",
    "left center",
    "left bottom",
    "right top",
    "right center",
    "right bottom",
    "center top",
    "center center",
    "center bottom",
  ],
  "background-attachment": ["scroll", "fixed", "local"],
  "background-clip": ["border-box", "padding-box", "content-box"],
  "background-origin": ["border-box", "padding-box", "content-box"],
  "background-size": ["auto", "cover", "contain"],
  "border-style": [
    "none",
    "hidden",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
  ],
  "border-collapse": ["collapse", "separate"],
  "outline-style": [
    "none",
    "dotted",
    "dashed",
    "solid",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
  ],
  "box-sizing": ["content-box", "border-box"],
  resize: ["none", "both", "horizontal", "vertical"],
  "text-overflow": ["clip", "ellipsis"],
  "text-decoration": ["none", "underline", "overline", "line-through"],
  "text-transform": ["none", "capitalize", "uppercase", "lowercase"],
  "text-align-last": ["auto", "left", "right", "center", "justify"],
  "text-justify": ["auto", "inter-word", "inter-character", "none"],
  "text-emphasis-style": [
    "none",
    "dot",
    "circle",
    "double-circle",
    "triangle",
    "sesame",
    "filled",
  ],
  "text-emphasis-position": ["over", "under"],
  "text-emphasis-color": ["currentColor", "red"],
  "text-indent": ["initial", "inherit"],
  "word-break": ["normal", "break-all", "keep-all"],
  "word-wrap": ["normal", "break-word"],
  hyphens: ["none", "manual", "auto"],
  "transition-property": ["none", "all", "property-name"],
  "transition-timing-function": [
    "linear",
    "ease",
    "ease-in",
    "ease-out",
    "ease-in-out",
  ],
  "animation-name": ["none", "animation-name"],
  "animation-timing-function": [
    "linear",
    "ease",
    "ease-in",
    "ease-out",
    "ease-in-out",
  ],
  "animation-iteration-count": [
    "initial",
    "infinite",
    "alternate",
    "alternate-reverse",
    "none",
  ],
  "animation-direction": [
    "normal",
    "reverse",
    "alternate",
    "alternate-reverse",
  ],
  "animation-fill-mode": ["none", "forwards", "backwards", "both"],
  "animation-play-state": ["running", "paused"],
  transform: ["none"],
  "transform-origin": ["50% 50%", "left top", "right bottom"],
  "backface-visibility": ["visible", "hidden"],
  perspective: ["none", "100px"],
  "perspective-origin": ["center", "top", "right", "bottom", "left"],
  "box-shadow": ["none", "10px 10px 5px 2px"],
  "text-shadow": ["none", "2px 2px 2px"],
  filter: [
    "none",
    "blur(5px)",
    "grayscale(50%)",
    "brightness(50%)",
    "opacity(50%)",
    "sepia(50%)",
  ],
  "user-select": ["auto", "none", "text", "contain", "all"],
  "scroll-behavior": ["auto", "smooth"],
  "scroll-snap-type": ["none", "mandatory", "proximity"],
  "scroll-snap-align": ["none", "start", "end", "center"],
  "scroll-snap-stop": ["normal", "always"],
  "scrollbar-width": ["auto", "thin", "none"],
  "scrollbar-color": ["auto", "red"],
  "caret-color": ["auto", "red"],
  content: ["none"],
  "counter-increment": ["none", "name"],
  "counter-reset": ["none", "name"],
  quotes: ["none", "initial", "auto"],
  "page-break-before": ["auto", "always", "avoid", "left", "right"],
  "page-break-after": ["auto", "always", "avoid", "left", "right"],
  "page-break-inside": ["auto", "avoid"],
  orphans: ["3", "auto"],
  widows: ["3", "auto"],
  "box-decoration-break": ["slice", "clone"],
  "break-inside": [
    "auto",
    "avoid",
    "avoid-page",
    "avoid-column",
    "avoid-region",
  ],
  "break-before": [
    "auto",
    "avoid",
    "always",
    "left",
    "right",
    "recto",
    "verso",
    "page",
    "column",
    "region",
    "avoid-page",
    "avoid-column",
    "avoid-region",
  ],
  "break-after": [
    "auto",
    "avoid",
    "always",
    "left",
    "right",
    "recto",
    "verso",
    "page",
    "column",
    "region",
    "avoid-page",
    "avoid-column",
    "avoid-region",
  ],
  "tab-size": ["8", "16"],
  "text-size-adjust": ["auto", "none"],
  "writing-mode": ["horizontal-tb", "vertical-rl", "vertical-lr"],
  "text-orientation": ["mixed", "upright", "sideways"],
  "text-combine-upright": ["none", "all"],
  "ruby-position": ["over", "under", "inter-character"],
  "ruby-align": ["start", "center", "space-around", "space-between"],
  "ruby-overhang": ["auto", "none", "either", "start", "end"],
  "ruby-span": ["none", "ruby", "segment"],
  "grid-template-columns": ["auto", "1fr", "200px", "200px 1fr 200px"],
  "grid-template-rows": ["auto", "1fr", "100px", "100px 1fr 100px"],
  "grid-template-areas": [
    "none",
    "'header header' 'content sidebar' 'footer footer'",
    "'header content' 'sidebar content' 'footer footer'",
  ],
  "grid-auto-columns": ["auto", "1fr", "200px"],
  "grid-auto-rows": ["auto", "1fr", "100px"],
  "grid-auto-flow": ["row", "column", "dense"],
  "grid-column-start": ["auto"],
  "grid-column-end": ["auto"],
  "grid-row-end": ["auto"],
  "grid-area": ["header", "content", "sidebar", "footer"],
  "justify-self": [
    "auto",
    "normal",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "center",
    "left",
    "right",
  ],
  "align-self": [
    "auto",
    "normal",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "center",
    "baseline",
  ],
  "place-self": [
    "auto",
    "normal",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "center",
    "baseline",
  ],
  "justify-items": [
    "auto",
    "normal",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "center",
    "baseline",
  ],
  "align-items": [
    "auto",
    "normal",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "center",
    "baseline",
  ],
  "place-items": [
    "auto",
    "normal",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "center",
    "baseline",
  ],
  "justify-content": [
    "flex-start",
    "flex-end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
  ],
  "align-content": [
    "flex-start",
    "flex-end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
  ],
  "place-content": [
    "center",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "space-between",
    "space-around",
    "space-evenly",
  ],
  gap: ["normal", "10px"],
  "row-gap": ["normal", "10px"],
  "column-gap": ["normal", "10px"],
  "flex-direction": ["row", "row-reverse", "column", "column-reverse"],
  "flex-wrap": ["nowrap", "wrap", "wrap-reverse"],
  "flex-flow": ["row nowrap", "column wrap", "row-reverse wrap-reverse"],
  order: ["initial", "inherit"],
  "flex-grow": ["0", "1"],
  "flex-shrink": ["1", "0"],
  "flex-basis": ["auto", "100px"],
  "grid-row-start": ["auto", "1"],
  "align-start": [
    "stretch",
    "start",
    "end",
    "flex-start",
    "flex-end",
    "self-start",
    "self-end",
    "baseline",
  ],
};
